language: clojure
lein: 2.6.1
jdk:
  - oraclejdk8
sudo: required
group: edge
git:
  submodules: false
cache:
  directories:
    - $HOME/.m2


script:
  - lein cljsbuild once min
  - git add resources/public && git commit -m "Initial dist subtree commit"
  - git subtree push --prefix resources/public origin gh-pages
